source_url: "public/data/dinesafe.csv"   
format: "csv"
years: 0                                  
field_map:
  
name: "establishment_name"
address: "establishment_address"
lat: "latitude"
lon: "longitude"
inspection_date: "inspection_date"
result: "outcome"

